import { MasterObjectService } from 'core/services/master-object.service';
import { FirestorecollectionService } from 'src/app/firestorecollection.service';
import { Router } from '@angular/router';
export class AbstractDashboardDef{
    
    constructor(public object: MasterObjectService,public firestorecollectionService:FirestorecollectionService,public router:Router) {
    }

    public design=[
        {design:'D1',name:'D1'},
        {design:'D1',name:'D1'},
        {design:'D1',name:'D1'},
        {design:'D1',name:'D1'},
        {design:'D2',name:'D2'},
        {design:'D3',name:'D3'},
        {design:'D4',name:'D4'},
        {design:'D4',name:'D4'},
        {design:'D4',name:'D4'},
        {design:'D4',name:'D4'},
        {design:'D5',name:'D5'},
        {design:'D6',name:'D6'},
        {design:'D7',name:'D7'},
        {design:'D8',name:'D8'},
    ]
    public domainDesign=[]
    public domainprimaryColor=[]
    public domainSecondryColor=[]
    public uxDesign='D1'

    public domains=[
        {
            domainName:'iceexchange.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'red'
        },
        {
            domainName:'dubaiexch99.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#c37601'
        },
        {
            domainName:'icecric.com',
            design:'D2',
            primaryColor:'#112e5d',
            secondryColor:'#ebbe00'
        },
        {
            domainName:'asiaexchange.com',
            design:'D4',
            primaryColor:'#000',
            secondryColor:'#ff8a00'
        },
        {
            domainName:'vipexch.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'green'
        },
        {
            domainName:'jetexch7.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#43a7c8'
        },
        {
            domainName:'sportzexch.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#dde328'
        },
        {
            domainName:'dynaexch.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#0188cc'
        },
        {
            domainName:'bullexch999.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#a020ef'
        },
        {
            domainName:'high5exch.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#e5943f'
        },
        {
            domainName:'googlyexch.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#a12b29'
        },
        {
            domainName:'lcexch9.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#4fa9dc'
        },
        {
            domainName:'icebetcare.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#ff00ff'
        },
        {
            domainName:'mgice.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#00f9fd'
        },
        {
            domainName:'multicric.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#ffb90c'
        },
        {
            domainName:'dubai365.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#f9a022'
        },
        {
            domainName:'pridecric.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#ffc629'
        },
        {
            domainName:'americanexch.com',
            design:'D2',
            primaryColor:'#0A3161',
            secondryColor:'#B31942'
        },
        {
            domainName:'prtcric.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#24d3d1'
        },
        {
            domainName:'lotuspunt247.com',
            design:'D2',
            primaryColor:'#006a0a',
            secondryColor:'#ffb322'
        },
        {
            domainName:'daddybook247.net',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#ff0000'
        },
        {
            domainName:'shyamcric.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#c62036'
        },
        {
            domainName:'jhonycric.com',
            design:'D2',
            primaryColor:'#19005c',
            secondryColor:'#e8970b'
        },
        {
            domainName:'dafapunt.com',
            design:'D2',
            primaryColor:'#ae0001',
            secondryColor:'#ffde04'
        },
        {
            domainName:'kalyancric.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#f79333'
        },
        {
            domainName:'punt99.com',
            design:'D2',
            primaryColor:'#20bfff',
            secondryColor:'#ffb322'
        },
        {
            domainName:'bajrangiwin.com',
            design:'D2',
            primaryColor:'#282828',
            secondryColor:'#fc6602'
        },
        {
            domainName:'dubaicric365.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#ff6e00'
        },
        {
            domainName:'kingcric.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#0e795b'
        },
        {
            domainName:'jetcric.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#3dc7f4'
        },
        {
            domainName:'bettingvilla.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#990707'
        },
        {
            domainName:'betcric.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#315195'
        },
        {
            domainName:'the100.com',
            design:'D4',
            primaryColor:'#373737',
            secondryColor:'#ffcc2f'
        },
        {
            domainName:'dream365.com',
            design:'D4',
            primaryColor:'#e00003',
            secondryColor:'#000'
        },
        {
            domainName:'jetexch365.com  ',
            design:'D4',
            primaryColor:'#000',
            secondryColor:'#1aeeed'
        },
        {
            domainName:'flipbet365.com',
            design:'D4',
            primaryColor:'#01d78f',
            secondryColor:'#000'
        },
        {
            domainName:'playexch9.co',
            design:'D4',
            primaryColor:'#000',
            secondryColor:'#e76f26'
        },
        {
            domainName:'playfair9.co',
            design:'D4',
            primaryColor:'#14805e',
            secondryColor:'#14805e'
        },
        {
            domainName:'45sports.io',
            design:'D4',
            primaryColor:'#315195',
            secondryColor:'#bb1c00'
        },
        {
            domainName:'jetexch9.in',
            design:'D4',
            primaryColor:'#000',
            secondryColor:'#16ACAB'
        },
        {
            domainName:'dream444.io',
            design:'D4',
            primaryColor:'#000',
            secondryColor:'#ffc629'
        },
        {
            domainName:'ostexch9.com',
            design:'D4',
            primaryColor:'#000',
            secondryColor:'#799f0c'
        },
        {
            domainName:'worldexch9.com',
            design:'D4',
            primaryColor:'#717070',
            secondryColor:'#ffcc2f'
        },
        {
            domainName:'armani9.com',
            design:'D4',
            primaryColor:'#000',
            secondryColor:'#f5d679'
        },
        {
            domainName:'playsports9.com',
            design:'D4',
            primaryColor:'#000',
            secondryColor:'#f6a21e'
        },
        {
            domainName:'rio.theicexch.com',
            design:'D4',
            primaryColor:'#315195',
            secondryColor:'#4F9F21'
        },
    ]


    // ''''




    public filterDomains=[
        {
            domainName:'iceexchange.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'red'
        },
        {
            domainName:'dubaiexch99.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#c37601'
        },
        {
            domainName:'icecric.com',
            design:'D2',
            primaryColor:'#112e5d',
            secondryColor:'#ebbe00'
        },
        {
            domainName:'asiaexchange.com',
            design:'D4',
            primaryColor:'#000',
            secondryColor:'#ff8a00'
        },
        {
            domainName:'vipexch.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'green'
        },
        {
            domainName:'jetexch7.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#43a7c8'
        },
        {
            domainName:'sportzexch.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#dde328'
        },
        {
            domainName:'dynaexch.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#0188cc'
        },
        {
            domainName:'bullexch999.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#a020ef'
        },
        {
            domainName:'high5exch.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#e5943f'
        },
        {
            domainName:'googlyexch.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#a12b29'
        },
        {
            domainName:'lcexch9.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#4fa9dc'
        },
        {
            domainName:'icebetcare.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#ff00ff'
        },
        {
            domainName:'mgice.com',
            design:'D1',
            primaryColor:'#000',
            secondryColor:'#00f9fd'
        },
        {
            domainName:'multicric.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#ffb90c'
        },
        {
            domainName:'dubai365.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#f9a022'
        },
        {
            domainName:'pridecric.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#ffc629'
        },
        {
            domainName:'americanexch.com',
            design:'D2',
            primaryColor:'#0A3161',
            secondryColor:'#B31942'
        },
        {
            domainName:'prtcric.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#24d3d1'
        },
        {
            domainName:'lotuspunt247.com',
            design:'D2',
            primaryColor:'#006a0a',
            secondryColor:'#ffb322'
        },
        {
            domainName:'lotuspunt247.com',
            design:'D2',
            primaryColor:'#006a0a',
            secondryColor:'#ff0000'
        },
        {
            domainName:'shyamcric.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#c62036'
        },
        {
            domainName:'jhonycric.com',
            design:'D2',
            primaryColor:'#19005c',
            secondryColor:'#e8970b'
        },
        {
            domainName:'dafapunt.com',
            design:'D2',
            primaryColor:'#ae0001',
            secondryColor:'#ffde04'
        },
        {
            domainName:'kalyancric.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#f79333'
        },
        {
            domainName:'punt99.com',
            design:'D2',
            primaryColor:'#20bfff',
            secondryColor:'#ffb322'
        },
        {
            domainName:'bajrangiwin.com',
            design:'D2',
            primaryColor:'#282828',
            secondryColor:'#fc6602'
        },
        {
            domainName:'bajrangiwin.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#ff6e00'
        },
        {
            domainName:'kingcric.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#0e795b'
        },
        {
            domainName:'jetcric.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#3dc7f4'
        },
        {
            domainName:'bettingvilla.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#990707'
        },
        {
            domainName:'betcric.com',
            design:'D2',
            primaryColor:'#000',
            secondryColor:'#315195'
        },
        {
            domainName:'the100.com',
            design:'D4',
            primaryColor:'#000',
            secondryColor:'#ffcc2f'
        }
    ]

    public themeBorder='2px solid red'
    public themeBackground:'black'
    public themeTextColor:'red'
    public sc='yellow'
    public pc='red'
    public selectedDomain=''

    public gameType=['SPORTS','ACE CASINO','LIVE CASINO','SLOTS','GAMES']
    public gameTyped4=['Home','Inplay','Market','Cricket','Soccer','Tennis','Casino']
}